<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="NativeUsbAssets.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>false</InvariantGlobalization>
    <AssemblyName>geekflash</AssemblyName>
    <RootNamespace>GeekFlashCore.CLI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GeekFlashCore.Android.Lp\GeekFlashCore.Android.Lp.csproj" />
    <ProjectReference Include="..\GeekFlashCore.FileSystem.Erofs\GeekFlashCore.FileSystem.Erofs.csproj" />
    <ProjectReference Include="..\GeekFlashCore.FileSystem.Ext\GeekFlashCore.FileSystem.Ext.csproj" />
    <ProjectReference Include="..\GeekFlashCore.Protocol.Abstractions\GeekFlashCore.Protocol.Abstractions.csproj" />
    <ProjectReference Include="..\GeekFlashCore.Protocol.Qcom\GeekFlashCore.Protocol.Qcom.csproj" />
    <ProjectReference Include="..\GeekFlashCore.Protocol.Mtk\GeekFlashCore.Protocol.Mtk.csproj" />
    <ProjectReference Include="..\GeekFlashCore.Protocol.Mtk.Extensions\GeekFlashCore.Protocol.Mtk.Extensions.csproj" />
    <ProjectReference Include="..\GeekFlashCore.Protocol.Qcom.Abstractions\GeekFlashCore.Protocol.Qcom.Abstractions.csproj" />
    <ProjectReference Include="..\GeekFlashCore.Transport.SerialPort\GeekFlashCore.Transport.SerialPort.csproj" />
    <ProjectReference Include="..\GeekFlashCore.Transport.LibUsb\GeekFlashCore.Transport.LibUsb.csproj" />
    <ProjectReference Include="..\GeekFlashCore.UsbWatcher\GeekFlashCore.UsbWatcher.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>
</Project>
