<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GeekFlashCore.Shared\GeekFlashCore.Shared.csproj" />
      <ProjectReference Include="..\GeekFlashCore.Transport.Abstractions\GeekFlashCore.Transport.Abstractions.csproj" />
    </ItemGroup>

</Project>
