<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GeekFlashCore.Protocol.Mtk.Abstractions/GeekFlashCore.Protocol.Mtk.Abstractions.csproj" />
    <ProjectReference Include="../GeekFlashCore.Shared/GeekFlashCore.Shared.csproj" />
    <ProjectReference Include="../GeekFlashCore.Gpt/GeekFlashCore.Gpt.csproj" />
    <ProjectReference Include="../GeekFlashCore.Android.Sparse/GeekFlashCore.Android.Sparse.csproj" />
    <ProjectReference Include="../GeekFlashCore.BlockDevice/GeekFlashCore.BlockDevice.csproj" />
  </ItemGroup>
</Project>
