<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GeekFlashCore.Transport.Abstractions\GeekFlashCore.Transport.Abstractions.csproj" />
      <ProjectReference Include="..\GeekFlashCore.UsbWatcher.Abstractions\GeekFlashCore.UsbWatcher.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MessagePipe" Version="1.8.2" />
      <PackageReference Include="Serilog" Version="4.4.0" />
    </ItemGroup>

</Project>
